In [2]:
import numpy as np

print("Hello worlds!")

Hello worlds!


In [63]:
#Array initialization (matrix if multidimensional)
"""
There are a lot of ways to do this. Here are some examples:
*Note: all of this are able to change dtype, using ",dtype=..." in the ()
"""

a = np.array([2,4,6])   #n-d array using .array(["content of array"])
b = np.array([[x for x in range(5)], [x for x in range(21,11,-2) if x%2!=0]])    #outside [] bracket if more than 1 row
print(a)
print(b)

[2 4 6]
[[ 0  1  2  3  4]
 [21 19 17 15 13]]


In [96]:
#some ways to extract some properties
x = np.random.random((4,4)).round(2)

print(x)            #prints out the array
print(x.shape)      #return size of array
print(x.max())      #return max of array
print(x.min())      #return min of array
print(x.ndim)       #return dim of array
print(x.size)       #return no of elms of array
print(x.diagonal()) #return an array of diagonal of x
print(x.dtype)      #return dtype of all elements in x  
print(np.sum(x))    #return sum of all elements in x   



[[0.58 0.88 0.02 0.24]
 [0.79 0.33 0.34 0.39]
 [0.54 0.12 0.8  0.43]
 [0.56 0.16 0.72 0.63]]
(4, 4)
0.88
0.02
2
16
[0.58 0.33 0.8  0.63]
float64
7.53


In [20]:
#for 1d array, we also have this
x = np.arange(10)       #.arange() functions the same as the normal .range() in normal Python
y = np.arange(0,10)
z = np.arange(0,10,1)

print(x)
print(y)
print(z)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [55]:
#Create a 1-D array of n evenly spaced elements from a to b
a = 3.  #would recommend to be float, so it could be spaced easier
b = 20
n = 17
x = np.linspace(a, b, n)
print(x)

[ 3.      4.0625  5.125   6.1875  7.25    8.3125  9.375  10.4375 11.5
 12.5625 13.625  14.6875 15.75   16.8125 17.875  18.9375 20.    ]


In [56]:
#create a matrix with diagonal = a given array
x = np.diag([3, 5, 4])      #len of array = dim of matrix
print(x)

[[3 0 0]
 [0 5 0]
 [0 0 4]]


In [85]:
#if u need diag = array & elsewhere = 0:
diagonal = [1, 2, 3, 4]
x = np.diagflat(diagonal)
#x = np.diagflat(x)         #very intersting :v
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [25]:
#create a identity matrix with n-dim 
n = 3
x = np.identity(n, dtype=int)       #default dtype is float, change if needed
y = np.eye(n, dtype=int)

print(x)
print("\n")
print(y)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [45]:
#create an array fulls of 0's or 1's
dim = (2,3)                         #more "," then more dim   #Note: can change () in dim with []
full_0 = np.zeros((2,3))            #param is dim of array (row,col)
full_1 = np.ones(dim, dtype=int)    #can also change dtype

print("For 0's and 1's: ")
print(full_0)
print(full_1)
print("\n")


print("For the note: ")
#if u alraeady have a matrix, u can fill them with 0's or 1's with this
example = np.array([[x for x in range(5)], [x for x in range(21,11,-2) if x%2!=0]])

another_0 = np.zeros_like(example)
another_1 = np.ones_like(example)

print(example)
print(another_0)
print(another_1)

For 0's and 1's: 
[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1]
 [1 1 1]]


For the note: 
[[ 0  1  2  3  4]
 [21 19 17 15 13]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [38]:
#or instead of 0 or 1, we need a array with n. hence, we'll use .full()
dim = (3,2,2)
n = 10
x = np.full(dim,n, dtype=int)  
print(x)

y = np.full((2,2),4)
print(y)


#another very creative way to create like y
z = np.ones((2, 2), dtype=int)*4
print(z)

[[[10 10]
  [10 10]]

 [[10 10]
  [10 10]]

 [[10 10]
  [10 10]]]
[[4 4]
 [4 4]]
[[4 4]
 [4 4]]


In [61]:
#create an array with arbitrary value
a = np.random.random((2,2))    #value from [0,1)
print(a)

a = a.round(2)      #can round like this (a is numpy array), param is no of decimals
print(a)


[[0.4505613  0.53954959]
 [0.15419156 0.43819205]]
[[0.45 0.54]
 [0.15 0.44]]


In [81]:
#accessing numpy array
x = np.random.random((4,4)).round(2)

a = x[2,2]      #access value in (2,2) of x
b = x[:2,:2]    #make new array from row 2 and col 2 onwards
c = x[2:,3:]    #make new array from row 2 and col 3 backwards

print(x)
print(a)
print(b)
print(c)

[[0.38 0.86 0.07 0.99]
 [0.97 0.7  0.43 0.24]
 [0.88 0.44 0.04 0.71]
 [0.7  0.33 0.67 0.92]]
0.04
[[0.38 0.86]
 [0.97 0.7 ]]
[[0.71]
 [0.92]]


In [92]:
#some mathematical method with numpy array
x = np.random.random((3,3)).round(2)
y = np.random.random((3,3)).round(2)

print("x = ", x)
print("y = ", y)
print("\n")

#every basic methods (+ - * / sqrt() , **) works in this way
print(x*y)                  #note: this is NOT dot product! it does x[i]*y[i] 
print(np.dot(x,y))          #the same as x.dot(y)
print(np.log(x))            #return loge of every elements
print(np.abs(x))            #return absolute value of every elements
print(np.linalg.inv(x))     #return the inverse matrix of x
print(y.T)                  #return the transpose matrix of y

x =  [[0.15 0.68 0.69]
 [0.45 0.58 0.7 ]
 [0.59 0.13 0.41]]
y =  [[0.63 0.35 0.72]
 [0.17 0.37 0.5 ]
 [0.33 0.49 0.42]]


[[0.0945 0.238  0.4968]
 [0.0765 0.2146 0.35  ]
 [0.1947 0.0637 0.1722]]
[[0.4378 0.6422 0.7378]
 [0.6131 0.7151 0.908 ]
 [0.5291 0.4555 0.662 ]]
[[-1.89711998 -0.38566248 -0.37106368]
 [-0.7985077  -0.54472718 -0.35667494]
 [-0.52763274 -2.04022083 -0.89159812]]
[[0.15 0.68 0.69]
 [0.45 0.58 0.7 ]
 [0.59 0.13 0.41]]
[[ -7.99869231  10.30349262  -4.13011497]
 [-12.45028061  18.83070888 -11.1970795 ]
 [ 15.45796328 -20.79768975  11.93265406]]
[[0.63 0.17 0.33]
 [0.35 0.37 0.49]
 [0.72 0.5  0.42]]


In [95]:
#some other ways to create an array with arbitrary value
dim = (3,3)
a = 5
b = 15
n = 50

x = np.random.randn(a,b)            #a (a x b) matrix with value from normal distribution 
y = np.random.randint(a,b,dim)      #a (dim) matrix with value from a to b
z = np.random.permutation(n)        #an array, which elements are random permutation of (1,2,...,n)

print(x)
print(y)
print(z)

[[-1.88409948 -1.11775113 -0.34214511 -1.27457282 -0.93272162  2.36532405
  -0.95531535 -1.53423717  1.07490372  0.86315604 -0.00827828 -1.73910618
   1.82311462 -0.57925216  0.37939173]
 [-0.96398874  0.07273422 -2.55682062  1.24956799  0.4686245  -0.97329881
  -1.01556471 -0.39115646 -0.14442013 -2.49425781 -1.14601236 -1.29466634
   0.85735675 -0.22461404  1.11362299]
 [-0.09483308  1.25775506 -0.11684153  1.6201849  -0.23443301 -0.34740367
  -0.05370451 -0.01641299 -0.24442006 -0.85249535 -0.66348338  0.02649149
  -0.76925637  0.76387801  0.93936295]
 [-0.0389624   0.26179908 -0.0466968   0.81626242  0.32347677 -0.68086876
  -0.72817333  0.35491359  1.22472458 -0.47871428 -0.06752208 -0.24952249
  -0.00661188 -0.72926581  0.7338651 ]
 [-1.59966255 -1.57329702 -1.17076778  0.23347549  1.148969   -1.30647571
   0.58978788 -1.68190565  0.96210512 -0.78101572  1.30988189 -1.3439469
   0.64733484  0.28634654  0.76033041]]
[[ 7  9  5]
 [ 9 13 10]
 [14  8 12]]
[47 43 17 37 36 27 40 34 41 

In [97]:
#finding sum by axis
x = np.random.random((3,3)).round(2)
print(np.sum(x, axis=0))    #=0 means calc by every rows
print(np.sum(x, axis=1))    #=1 means calc by every cols

[1.71 1.27 1.33]
[1.91 0.72 1.68]


In [104]:
#filtering elements by conditions 
#we can make use of [] from slicing/accessing members

x = np.random.random((3,3)).round(2)
print(x)

condition = ((x-0.5)>=0)         #condition must be bracketed with ()
                                #must also include the array we have
                                
print(condition)                #return bool array  according to the condition
print(x[condition])             #return a filtered array which keep the elements that == True
print(x[((x-0.5)>=0)])           #or just directly writing the condition

[[0.55 0.5  0.14]
 [0.55 0.26 0.21]
 [0.77 0.93 0.4 ]]
[[ True  True False]
 [ True False False]
 [ True  True False]]
[0.55 0.5  0.55 0.77 0.93]
[0.55 0.5  0.55 0.77 0.93]


In [114]:
#reshaping array/matrix
x = np.random.random((3,4)).round(2)
print(x)

x = x.reshape(4,3)
print(x)



[[0.01 0.81 0.5  0.51]
 [0.69 0.05 0.52 0.95]
 [0.38 0.67 0.31 0.2 ]]
[[0.01 0.81 0.5 ]
 [0.51 0.69 0.05]
 [0.52 0.95 0.38]
 [0.67 0.31 0.2 ]]


In [120]:
#concatenating arrays
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
ans1 = np.concatenate((x, y), axis=0)       #=0 means by rows
ans2 = np.concatenate((x, y), axis=1)       #=1 means by cols

print(ans1)
print(ans2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
