In [ ]:
num_list = [34, 11, 35, 89]
name_list = ['Zen Jack', 'Luigi Austin', 'Ben Benson', 'John Ann']

id_name_list = list(zip(num_list, name_list))
id_name_list


[(34, 'Zen Jack'), (11, 'Luigi Austin'), (35, 'Ben Benson'), (89, 'John Ann')]

In [ ]:
sorted(id_name_list, key=lambda x: x[1])

# x --> (35, 'Ben Benson'), x[1] --> 'Ben Benson'

[(35, 'Ben Benson'), (89, 'John Ann'), (11, 'Luigi Austin'), (34, 'Zen Jack')]

In [ ]:
num_list

[11, 34, 35, 37, 89]

In [ ]:
num_list = [22, 34, 11, 35, 89, 37, 93, 56, 108]


In [ ]:
sorted(num_list, key=lambda x: x%10)

[11, 22, 93, 34, 35, 56, 37, 108, 89]

In [ ]:
# list of tuple (width, height, image_data)

# sort list of tuple by image size = width * height
import numpy as np

img_datasets = [(10, 20, np.random.rand(10, 20)),
                (30, 5, np.random.rand(30, 5)),
                 (10, 2, np.random.rand(10, 2))]

sorted(img_datasets, key=lambda x: x[0] * x[1])

In [ ]:
name_list = ['Zen Jack', 'Luigi Austin', 'Ben Benson', 'John Ann']

# sort by len of the last name
sorted(name_list, key=lambda x: len(x.split()[1]))

['John Ann', 'Zen Jack', 'Luigi Austin', 'Ben Benson']

## classes

In [ ]:
class Bag:
    def __init__(self, init_data=[]):
        self.data = init_data
        self.len = len(self.data)

    def add(self, x):
        self.data.append(x)
        self.len = len(self.data)

    def addtwice(self, x):
        self.add(x)
        self.add(x)


In [ ]:
instance = Bag(['a', 'b', 'c'])
instance.data, instance.len
instance.add(1)
instance.add('two')
instance.data, instance.len
# instance.addtwice(3)
# instance.data

(['a', 'b', 'c', 1, 'two'], 5)

In [ ]:
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.datasets import load_iris


In [ ]:
X, y = load_iris(return_X_y=True)
X.shape, y.shape

((150, 4), (150,))

In [ ]:
clf = HistGradientBoostingClassifier().fit(X, y)

instance = HistGradientBoostingClassifier()
clf = instance.fit(X, y)
# clf.score(X, y)


In [ ]:
clf, instance

(HistGradientBoostingClassifier(), HistGradientBoostingClassifier())

In [ ]:
clf.predict(X), y

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2

In [ ]:
# parent class
class Person():
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def display(self):
    print(self.name, self.age)

# child class
class Student(Person):
  def __init__(self, name, age):
    self.sName = name
    self.sAge = age
    # inheriting the properties of parent class
    super().__init__("Rahul", age)

  def displayInfo(self):
    print(self.sName, self.sAge)

In [ ]:
student = Student('Student', 20)
student.name, student.age , student.sName, student.sAge

('Rahul', 20, 'Student', 20)

In [ ]:
import torch.nn as nn
import torch.nn.functional as F

class CNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 20, 5)
        self.conv2 = nn.Conv2d(20, 20, 5)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        return F.relu(self.conv2(x))


In [ ]:
import torch
cnn_model = CNN()
out = cnn_model.forward(torch.rand(10, 1, 28, 28))
out.shape


torch.Size([10, 20, 20, 20])

In [ ]:
import random

indexes = list(range(len(X)))
random.shuffle(indexes)
list(range(len(indexes)))[::3]

In [78]:
import numpy as np

class CustomDataLoader:
  def __init__(self, inputs, targets):
    self.indexes = list(range(len(inputs)))

  def shuffle(self):
      random.shuffle(self.indexes)

  def get_iter(self, batch_size = 1):
      for start in range(0, len(self.indexes), batch_size):
        if start + batch_size <= len(self.indexes):
          # X_b = [X[id] for id in self.indexes[start:start+batch_size]]
          # y_b = [y[id] for id in self.indexes[start:start+batch_size]]

          X_b  = X[np.array(self.indexes[start:start+batch_size])]
          y_b = y[np.array(self.indexes[start:start+batch_size])]

          yield X_b, y_b, self.indexes[start:start+batch_size]



In [86]:
indexes = np.arange(100)
np.random.shuffle(indexes)
indexes


array([13, 18, 84, 21, 33,  0,  1, 24, 77,  5,  4, 92, 90, 47, 53, 91, 19,
       10, 82, 76, 38, 16, 62, 88, 65, 26, 48, 14, 99, 56, 61, 83, 37, 96,
       68, 45, 28, 46, 12, 22, 67,  3, 43, 11,  9, 55, 39,  6, 20, 74, 66,
       36, 78, 57,  2, 23, 17, 30, 97, 59, 75, 31, 98, 44, 50, 95, 27, 93,
       63, 71, 34, 89, 32, 69, 60,  7, 94, 29, 70, 73, 86, 35, 85, 49, 80,
       64, 58, 87, 81, 52, 79, 40, 25, 72, 51, 41, 15, 54, 42,  8])

In [87]:
class CustomDataLoaderNP:
  def __init__(self, inputs, targets):
    self.indexes = np.arange(len(inputs))

  def shuffle(self):
      np.random.shuffle(self.indexes)

  def get_iter(self, batch_size = 1):
      for start in range(0, len(self.indexes), batch_size):
        if start + batch_size <= len(self.indexes):

          X_b  = X[self.indexes[start:start+batch_size]]
          y_b = y[self.indexes[start:start+batch_size]]

          yield X_b, y_b, self.indexes[start:start+batch_size]

In [88]:
## Implement a dataloader
## Shuffle, divide data into batches,

X, y = load_iris(return_X_y=True)
X.shape, y.shape

data_loader = CustomDataLoaderNP(X, y)

data_loader.shuffle()
data_loader.indexes

counter = 0
for X_b, y_b, id_b in data_loader.get_iter(7):
  print (X_b.shape, y_b.shape)
  # print (id_b)
  counter += 1

counter


(7, 4) (7,)
(7, 4) (7,)
(7, 4) (7,)
(7, 4) (7,)
(7, 4) (7,)
(7, 4) (7,)
(7, 4) (7,)
(7, 4) (7,)
(7, 4) (7,)
(7, 4) (7,)
(7, 4) (7,)
(7, 4) (7,)
(7, 4) (7,)
(7, 4) (7,)
(7, 4) (7,)
(7, 4) (7,)
(7, 4) (7,)
(7, 4) (7,)
(7, 4) (7,)
(7, 4) (7,)
(7, 4) (7,)


21

In [73]:
21*7

147

In [71]:
counter

50